name: Flask CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1.checkout my code
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # 2.Setup python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flask_sqlalchemy

    # 4. Run tests
    - name: Run pytest
      run: |
        pytest -v
